name: VShred

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: VShred

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install V
      run: |
        git clone https://github.com/vlang/v
        cd v
        make
    - name: build VShred
      run: ./v/v vshred.v