name: VShred

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install V
      run: |
        git clone https://github.com/vlang/v
        cd v
        .\make.bat -tcc
    - name: build VShred
      run: ./v/v vshred.v